# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
