# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppliances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('qty', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
