# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userappliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliances',
            name='user',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
