# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170430_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappliances',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
